
title: Kang Liao


#sidebar links
email: kang_liao AT bjtu DOT edu DOT cn
#phone: 012 345 6789
#linkedin: alandoe
website_zhihu: ZHIHU
website_csdn: CSDN
website_google: Google Scholar
port: 4001
#Update all the sections by editing the files inside _includes folder.
